### PR TITLE
Add page to explain experiments.py more

### PR DESCRIPTION
**Pull request by gecock**
added a markdown page to explain how `experiments.py` works in more detail than the README states.

### CODE REVIEW

**Review by tnixa — APPROVED** [review]

**Comment by lmazzoli** [comment]
@gecock This is very clear -- thanks!  One suggestion would be to make the customization weight example use the values of 0.0 - 0.3.  Technically, the service says the value can be between 0.0 and 1.0

**Comment by gecock** [comment]
Good catch @lmazzoli ... I guess I mistook customization weight and character insertion bias. Wonder why I didn't get an error on the API call. @tnixa suggested adding variable validation to the script which is a good idea I'll work on in a new PR.

I'll redo the example an get a new commit out

**Review by lmazzoli — APPROVED** [review]

**Review by andrewrfreed — COMMENTED** [review]
@gecock on the sample configuration, it looks like there are spaces in your example.  If the user copy/pastes those into their own config file, will those "extra" spaces still work?

Otherwise thank you for the documentation and feel free to merge.

**Comment by gecock** [comment]
@andrewrfreed The config has underscores for the variable names. Is that what you're referring to? 

Also, I don't have the authorization to merge into `main`.

**Review by andrewrfreed — APPROVED** [review]
Thanks for offline clarification!

**Pull request merged**
